server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: 464646546
    keyId: 121554654
    keySecret: adfsdafsafa
    bucketName: srb-file
